properties([
  disableConcurrentBuilds(abortPrevious: true)
])

timeout(time: 24, unit: 'HOURS') {
  buildPod(context: 'ci', gpus: 1, devShm: true,
    buildArgs: '--build-arg SPACK_INSTALL_PROCESSES=2 --build-arg SPACK_INSTALL_JOBS=2') {
    withEnv([
      "HOME=$WORKSPACE",
      "ABACUS=$WORKSPACE",
      "ABACUS_TMP=/dev/shm/",
      "ABACUS_PERSIST=/dev/shm",
      "ABACUS_SSD=/dev/shm"
    ]) {
      timeout(time: 1, unit: 'HOURS') {
        stage('Build') {
                sh '''
                    . /opt/spack-environment/activate.sh
                    export PYTHONPATH=$ABACUS:$PYTHONPATH OMP_NUM_THREADS=$PARALLEL

                    cd $ABACUS/external/zeldovich-PLT
                    meson setup build
                    meson compile -v -C build -j $PARALLEL

                    cd $ABACUS
                    ./configure
                    make ABACUS_CPPFLAGS=-Werror

                    cd Production/site_files
                    ln -s jenkins.def site.def
                '''
        }
        stage('Test') {
                sh '''
                    . /opt/spack-environment/activate.sh
                    export PYTHONPATH=$ABACUS:$PYTHONPATH OMP_NUM_THREADS=$PARALLEL

                    cd $ABACUS/Tests/Ewald
                    ./run_ewald.py --no-plot

                    cd $ABACUS/Tests/CheckForces
                    ./check_forces.py 64 17 --no-plot

                    cd $ABACUS/Tests/Spiral
                    ./SpiralTest.py --no-plot
                '''
        }
      }
    }
  }
}
